#pragma once

#include <Arduino.h>

const char EASE_DASHBOARD_HTML[] PROGMEM = R"EASEHTML(
<!doctype html>
<html lang="fr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#081315">
<title>EASE — Qualité de l’air</title>
<style>
:root{--bg:#071113;--panel:#0d1b1e;--panel2:#102327;--line:#244047;--text:#edf8f6;--muted:#8eaaa8;--green:#38d996;--yellow:#f2cf5b;--orange:#ff8c42;--red:#ff4f5e;--co2:#58e0ac;--voc:#f5c95a;--hcho:#ff7085;--pm1:#70b7ff;--pm25:#a98bff;--pm10:#ff9066;--temp:#ffb25f;--hum:#62c9ff;--radius:18px}
*{box-sizing:border-box}html{background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}body{margin:0;min-height:100vh;background:radial-gradient(circle at 12% -10%,#16423d 0,transparent 34rem),var(--bg)}
.shell{width:min(1480px,100%);margin:auto;padding:24px}.top{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:20px}.brand{display:flex;align-items:center;gap:14px}.mark{width:48px;height:48px;border-radius:15px;background:linear-gradient(145deg,#58efb5,#23866e);display:grid;place-items:center;color:#062019;font-weight:900;letter-spacing:-1px;box-shadow:0 10px 30px #38d99626}.brand h1{font-size:clamp(20px,3vw,31px);margin:0;letter-spacing:-.8px}.brand p{margin:3px 0 0;color:var(--muted);font-size:13px}.live{display:flex;align-items:center;gap:9px;color:var(--muted);font-size:13px}.dot{width:9px;height:9px;border-radius:50%;background:var(--green);box-shadow:0 0 0 6px #38d9961d}.dot.stale{background:var(--red);box-shadow:0 0 0 6px #ff4f5e1d}
.hero{display:grid;grid-template-columns:minmax(0,1.25fr) minmax(190px,.55fr) minmax(0,.8fr);gap:16px;margin-bottom:16px}.quality,.ventilation,.pmavg,.panel,.event-panel{background:linear-gradient(150deg,#102326e8,#0b191ce8);border:1px solid #254148b8;border-radius:var(--radius);box-shadow:0 18px 55px #0005}.quality{padding:22px;display:grid;grid-template-columns:1fr auto;gap:18px;align-items:center}.eyebrow{text-transform:uppercase;letter-spacing:1.5px;font-size:11px;color:var(--muted);font-weight:700}.qtitle{display:flex;align-items:baseline;gap:11px;margin:5px 0 13px}.qtitle strong{font-size:clamp(28px,4vw,45px);letter-spacing:-1.7px}.qtitle span{color:var(--muted)}.scale{height:12px;border-radius:99px;background:linear-gradient(90deg,var(--green),var(--yellow) 37%,var(--orange) 67%,var(--red));position:relative}.needle{position:absolute;top:-5px;width:4px;height:22px;border-radius:3px;background:white;box-shadow:0 0 12px #fff;left:0;transition:left .5s ease}.qdetail{font-size:13px;color:var(--muted);margin-top:12px}.qbadge{width:70px;height:70px;border-radius:22px;background:#38d99620;border:1px solid #38d99660;display:grid;place-items:center;font-size:25px;font-weight:900;transition:.4s}.ventilation{padding:20px;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;gap:8px;transition:background .45s,border-color .45s,box-shadow .45s}.vent-dot{width:38px;height:38px;border-radius:50%;background:#263b40;border:1px solid #456169;position:relative;transition:.45s}.vent-dot:after{content:"";position:absolute;inset:11px;border-radius:50%;background:#78918f}.vent-state{font-size:23px;font-weight:800;letter-spacing:-.6px}.vent-hint{font-size:11px;color:var(--muted)}.vent-legend{font-size:10px;color:#8fb7b6;margin-top:3px}.vent-legend:before{content:"";display:inline-block;width:12px;height:8px;border-radius:2px;background:#67e3e929;border:1px solid #67e3e955;margin-right:5px}.ventilation.active{background:linear-gradient(150deg,#1c5961,#123b42);border-color:#6bd9e5;box-shadow:0 15px 45px #4edce32a}.ventilation.active .vent-dot{background:#67e3e9;border-color:#c5ffff;box-shadow:0 0 0 8px #67e3e925,0 0 25px #67e3e980}.ventilation.active .vent-dot:after{background:white}.ventilation.active .vent-state{color:#bfffff}.pmavg{padding:22px}.pmavg .big{font-size:38px;font-weight:800;letter-spacing:-1.5px;margin:9px 0 1px}.pmavg .unit{font-size:14px;color:var(--muted)}.pmavg .foot{margin-top:14px;font-size:12px;color:var(--muted)}
.kpis{display:grid;grid-template-columns:repeat(8,minmax(100px,1fr));gap:10px;margin-bottom:16px}.kpi{background:#0d1c1f;border:1px solid #223b41;border-radius:14px;padding:13px 14px;min-width:0}.kpi label{display:block;font-size:11px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.kpi strong{display:block;margin-top:5px;font-size:20px;letter-spacing:-.5px}.kpi small{font-size:11px;color:var(--muted);font-weight:500}.charts{display:grid;grid-template-columns:1fr;gap:16px}.panel{padding:18px}.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:8px}.panel h2{margin:0;font-size:17px;letter-spacing:-.3px}.panel p{margin:4px 0 0;color:var(--muted);font-size:12px}.range{display:flex;gap:5px}.range button,.filters button{border:1px solid #315159;background:#102328;color:var(--muted);border-radius:9px;padding:7px 10px;cursor:pointer}.range button.active,.range button:hover,.filters button:hover{color:var(--text);border-color:#54ad98;background:#15342f}.chart-wrap{height:285px;position:relative}.chart-wrap canvas{width:100%;height:100%;display:block}
.statusline{display:flex;gap:9px;flex-wrap:wrap;margin:16px 0}.pill{border-radius:99px;padding:7px 11px;background:#102126;border:1px solid #27434a;color:var(--muted);font-size:12px}.pill.ok{color:#73e7b6;border-color:#2d6b59}.pill.bad{color:#ff8590;border-color:#7d3a43}
.event-panel{margin-top:16px;padding:20px}.event-head{display:flex;justify-content:space-between;align-items:flex-start;gap:15px;margin-bottom:15px}.event-head h2{margin:0;font-size:19px}.event-head p{margin:4px 0 0;color:var(--muted);font-size:12px}.filters{display:flex;gap:8px;flex-wrap:wrap}.filters select,.filters input{border:1px solid #315159;background:#0d1c20;color:var(--text);border-radius:9px;padding:8px}.tables{display:grid;grid-template-columns:1fr;gap:18px}.subhead{font-size:13px;color:#b9cfcc;margin:5px 0 9px}.table-scroll{overflow:auto;border:1px solid #203a40;border-radius:12px}table{width:100%;border-collapse:collapse;min-width:760px;font-size:12px}th,td{text-align:left;padding:11px 12px;border-bottom:1px solid #1d3439;white-space:nowrap}th{color:var(--muted);font-weight:600;background:#0b181b;position:sticky;top:0}tr:last-child td{border-bottom:0}.empty{text-align:center!important;color:var(--muted);padding:25px!important}.level{display:inline-flex;align-items:center;gap:6px}.level:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--red)}
.error{display:none;background:#38171b;color:#ffadb4;border:1px solid #74343b;padding:12px 14px;border-radius:12px;margin-bottom:15px}.error.show{display:block}.footer{display:flex;justify-content:space-between;gap:20px;color:#6f8c89;font-size:11px;padding:20px 4px 8px}
@media(max-width:1050px){.kpis{grid-template-columns:repeat(4,1fr)}.hero{grid-template-columns:1fr}.qbadge{width:65px;height:65px;border-radius:19px}}
@media(max-width:650px){.shell{padding:14px}.top{align-items:flex-start}.live{margin-top:7px}.brand p{display:none}.kpis{grid-template-columns:repeat(2,1fr)}.quality{padding:17px}.qbadge{display:none}.chart-wrap{height:250px}.panel{padding:14px}.panel-head,.event-head{flex-direction:column}.footer{flex-direction:column}.range{width:100%}.range button{flex:1}}
</style>
</head>
<body>
<main class="shell">
  <header class="top">
    <div class="brand"><div class="mark">E</div><div><h1>EASE Air Lab</h1><p>Station autonome · XIAO ESP32S3</p></div></div>
    <div class="live"><span id="liveDot" class="dot stale"></span><span id="lastUpdate">Connexion…</span></div>
  </header>
  <div id="error" class="error"></div>
  <section class="hero">
    <article class="quality">
      <div><div class="eyebrow">Qualité de l’air intérieur</div><div class="qtitle"><strong id="qualityLabel">—</strong><span id="qualityCause">En attente</span></div><div class="scale"><i id="needle" class="needle"></i></div><div class="qdetail" id="qualityDetail">L’indice EASE suit le paramètre le plus défavorable.</div></div>
      <div id="qbadge" class="qbadge">—</div>
    </article>
    <article id="ventCard" class="ventilation"><span class="vent-dot" aria-hidden="true"></span><div class="eyebrow">Ventilation</div><div id="ventState" class="vent-state">Inactive</div><div id="ventHint" class="vent-hint">Fenêtre et porte fermées</div><div class="vent-legend">Périodes claires sur les graphes</div></article>
    <article class="pmavg"><div class="eyebrow">PM2.5 · moyenne glissante 24 h</div><div class="big"><span id="pmavg">—</span> <span class="unit">µg/m³</span></div><div id="pmavgState" class="unit">Calcul en cours</div><div class="foot" id="historyCoverage">Couverture : —</div></article>
  </section>
  <section class="kpis">
    <div class="kpi"><label>CO₂</label><strong><span id="co2">—</span> <small>ppm</small></strong></div>
    <div class="kpi"><label>Indice VOC</label><strong><span id="voc">—</span> <small>/ 500</small></strong></div>
    <div class="kpi"><label>HCHO estimé · WSP2110</label><strong><span id="hcho">—</span> <small id="hchoUnit">non installé</small></strong></div>
    <div class="kpi"><label>PM1</label><strong><span id="pm1">—</span> <small>µg/m³</small></strong></div>
    <div class="kpi"><label>PM2.5</label><strong><span id="pm25">—</span> <small>µg/m³</small></strong></div>
    <div class="kpi"><label>PM10</label><strong><span id="pm10">—</span> <small>µg/m³</small></strong></div>
    <div class="kpi"><label>Température</label><strong><span id="temp">—</span> <small>°C</small></strong></div>
    <div class="kpi"><label>Humidité</label><strong><span id="humidity">—</span> <small>%</small></strong></div>
  </section>
  <section class="charts">
    <article class="panel"><div class="panel-head"><div><h2>Gaz et composés</h2><p>CO₂, VOC et HCHO estimé · trois échelles indépendantes · WSP2110 indicatif et non sélectif</p></div><div class="range" data-chart-range><button data-hours="1">1 h</button><button class="active" data-hours="6">6 h</button><button data-hours="24">24 h</button></div></div><div class="chart-wrap"><canvas id="chartGas" aria-label="Historique CO2 VOC et HCHO estimé"></canvas></div></article>
    <article class="panel"><div class="panel-head"><div><h2>Particules fines</h2><p>PM1, PM2.5 et PM10 · µg/m³</p></div></div><div class="chart-wrap"><canvas id="chartPm" aria-label="Historique des particules"></canvas></div></article>
    <article class="panel"><div class="panel-head"><div><h2>Confort intérieur</h2><p>Température et humidité · deux échelles indépendantes</p></div></div><div class="chart-wrap"><canvas id="chartClimate" aria-label="Historique température humidité"></canvas></div></article>
  </section>
  <div class="statusline"><span id="wifiPill" class="pill">Wi-Fi —</span><span id="hubPill" class="pill">Hub I²C —</span><span id="rtcPill" class="pill">RTC —</span><span id="sdPill" class="pill">microSD —</span><span id="sensorPill" class="pill">Capteurs —</span><span id="alarmPill" class="pill">Alarme —</span></div>
  <section class="event-panel">
    <div class="event-head"><div><h2>Journal des dépassements</h2><p>Durées calculées avec l’horloge RTC et conservées sur microSD.</p></div><div class="filters"><input id="eventDate" type="date" aria-label="Filtrer par date"><select id="eventSensor" aria-label="Filtrer par paramètre"><option value="">Tous les paramètres</option><option>CO2</option><option>VOC</option><option value="HCHO estime">HCHO estimé</option><option>PM2.5</option><option>PM2.5 24h</option><option>PM10</option></select><button id="clearFilters">Effacer</button><button id="exportCsv">Exporter CSV</button></div></div>
    <div class="tables">
      <div><div class="subhead">Synthèse quotidienne</div><div class="table-scroll"><table><thead><tr><th>Date</th><th>Paramètre</th><th>Durée cumulée</th><th>Maximum</th><th>Nombre</th></tr></thead><tbody id="dailyBody"><tr><td colspan="5" class="empty">Aucun dépassement enregistré</td></tr></tbody></table></div></div>
      <div><div class="subhead">Événements détaillés</div><div class="table-scroll"><table><thead><tr><th>Début</th><th>Paramètre</th><th>Durée</th><th>Seuil</th><th>Moyenne</th><th>Maximum</th><th>Fin</th></tr></thead><tbody id="eventBody"><tr><td colspan="7" class="empty">Aucun dépassement enregistré</td></tr></tbody></table></div></div>
    </div>
  </section>
  <footer class="footer"><span>EASE · Environmental Air Sensor for Education</span><span id="stationTime">Horloge station : —</span></footer>
</main>
<script>
const $=id=>document.getElementById(id);let historyData=[],eventsData=[],rangeHours=6,lastLive=null;
const colors=['#38d996','#f2cf5b','#ff8c42','#ff4f5e'];const qlabels=['Bon','Acceptable','Dégradé','Alerte'];
function valid(v){return v!==null&&v!==undefined&&v!==''&&Number.isFinite(+v)}function fmt(v,d=0){return valid(v)?(+v).toFixed(d):'—'}
function duration(sec){sec=Math.max(0,Math.round(+sec||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${h} h ${String(m).padStart(2,'0')} min`:m?`${m} min ${String(s).padStart(2,'0')} s`:`${s} s`}
function dt(epoch){if(!epoch)return'—';return new Intl.DateTimeFormat('fr-FR',{dateStyle:'short',timeStyle:'medium'}).format(new Date(epoch*1000))}
function dayKey(epoch){const d=new Date(epoch*1000);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function setPill(id,label,ok){const el=$(id);el.textContent=label;el.className='pill '+(ok?'ok':'bad')}
async function json(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error(`${r.status} ${r.statusText}`);return r.json()}
function updateLive(v){lastLive=v;['co2','voc','hcho','pm1','pm25','pm10','temp','humidity'].forEach(k=>$(k).textContent=fmt(v[k],k==='temp'||k==='humidity'||k==='hcho'?1:0));$('hchoUnit').textContent=v.hcho_enabled?'ppm':'non installé';$('pmavg').textContent=fmt(v.pm25_24h,1);$('pmavgState').textContent=!v.pm25_24h_ready?'Fenêtre de 24 h en cours de constitution':v.pm25_24h>=v.pm25_24h_limit?'Seuil journalier dépassé':'Sous le seuil journalier';$('historyCoverage').textContent=`Couverture : ${duration(v.history_seconds)} · ${v.history_count} mesures`;
 const q=Math.max(0,Math.min(3,+v.quality||0));$('qualityLabel').textContent=v.quality_label||qlabels[q];$('qualityCause').textContent=v.quality_cause?`Piloté par ${v.quality_cause}`:'Toutes les mesures';$('needle').style.left=`calc(${[5,36,67,96][q]}% - 2px)`;$('qbadge').textContent=['✓','!','!!','!!!'][q];$('qbadge').style.background=colors[q]+'20';$('qbadge').style.borderColor=colors[q]+'80';$('qbadge').style.color=colors[q];
 const ventilating=!!v.ventilation_active;$('ventCard').classList.toggle('active',ventilating);$('ventState').textContent=ventilating?'Active':'Inactive';$('ventHint').textContent=ventilating?'Fenêtre ou porte ouverte':'Fenêtre et porte fermées';
 $('lastUpdate').textContent=`Actualisé à ${new Date().toLocaleTimeString('fr-FR')}`;$('liveDot').className='dot';$('stationTime').textContent=`Horloge station : ${v.iso||'—'}`;setPill('wifiPill',v.ap_mode?`Point d’accès · ${v.ip}`:`Wi-Fi ${v.wifi_rssi} dBm · ${v.ip}`,true);setPill('hubPill',v.i2c_hub_ok?'Hub I²C opérationnel':'Hub I²C indisponible',v.i2c_hub_ok);setPill('rtcPill',v.rtc_ok?'RTC synchronisée':'RTC à vérifier',v.rtc_ok);setPill('sdPill',v.sd_ok?'microSD opérationnelle':'microSD indisponible',v.sd_ok);setPill('sensorPill',`${v.sensors_ok}/${v.sensors_total} capteurs`,v.sensors_ok===v.sensors_total);setPill('alarmPill',v.alarm?'Alarme sonore active':'Alarme au repos',!v.alarm);
 if(!historyData.length||historyData[historyData.length-1].t!==v.timestamp){historyData.push({t:v.timestamp,co2:v.co2,voc:v.voc,hcho:v.hcho,pm1:v.pm1,pm25:v.pm25,pm10:v.pm10,temp:v.temp,humidity:v.humidity,ventilation:ventilating});trimHistory();drawAll()}}
function trimHistory(){const cut=Date.now()/1000-rangeHours*3600;historyData=historyData.filter(p=>p.t>=cut)}
function axisRange(data,key){const keys=Array.isArray(key)?key:[key],vals=[];data.forEach(p=>keys.forEach(k=>{if(valid(p[k]))vals.push(+p[k])}));if(!vals.length)return[0,1];let min=Math.min(...vals),max=Math.max(...vals);if(min===max){min-=1;max+=1}const pad=(max-min)*.12;return[Math.max(0,min-pad),max+pad]}
function drawChart(id,series,axes){const c=$(id),box=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);if(!box.width||!box.height)return;c.width=box.width*dpr;c.height=box.height*dpr;const x=c.getContext('2d');x.scale(dpr,dpr);const w=box.width,h=box.height;const leftAxes=axes.filter(a=>a.side==='left'),rightAxes=axes.filter(a=>a.side!=='left');const L=48+Math.max(0,leftAxes.length-1)*42,R=20+rightAxes.length*47,T=49,B=30,PW=w-L-R,PH=h-T-B;x.clearRect(0,0,w,h);const data=historyData.filter(p=>p.t>=Date.now()/1000-rangeHours*3600);axes.forEach(a=>a.range=axisRange(data,a.keys||a.key));const chartT0=data.length?data[0].t:0,chartT1=data.length?Math.max(data[data.length-1].t,Date.now()/1000):1;if(data.length>1){x.fillStyle='#67e3e929';data.forEach((p,i)=>{if(!p.ventilation)return;const end=i+1<data.length?data[i+1].t:chartT1,x1=L+(p.t-chartT0)/(chartT1-chartT0)*PW,x2=L+(end-chartT0)/(chartT1-chartT0)*PW;if(x2>x1)x.fillRect(x1,T,x2-x1,PH)})}x.strokeStyle='#234047';x.lineWidth=1;x.fillStyle='#78918f';x.font='10px system-ui';for(let i=0;i<=4;i++){const y=T+PH*i/4;x.beginPath();x.moveTo(L,y);x.lineTo(L+PW,y);x.stroke();axes.forEach((a,j)=>{const val=a.range[1]-(a.range[1]-a.range[0])*i/4;const isLeft=a.side==='left',idx=isLeft?leftAxes.indexOf(a):rightAxes.indexOf(a),ax=isLeft?L-idx*42:L+PW+idx*47;x.fillStyle=a.color;x.textAlign=isLeft?'right':'left';x.fillText(fmt(val,val<100?1:0),ax+(isLeft?-5:5),y+3)})}axes.forEach((a,j)=>{const isLeft=a.side==='left',idx=isLeft?leftAxes.indexOf(a):rightAxes.indexOf(a),ax=isLeft?L-idx*42:L+PW+idx*47;x.strokeStyle=a.color+'99';x.beginPath();x.moveTo(ax,T);x.lineTo(ax,T+PH);x.stroke();x.save();x.fillStyle=a.color;x.font='10px system-ui';x.translate(ax+(isLeft?-34:38),T+PH/2);x.rotate(-Math.PI/2);x.textAlign='center';x.fillText(a.label,0,0);x.restore()});if(data.length>1){const t0=chartT0,t1=chartT1;[...series].sort((a,b)=>(a.z||0)-(b.z||0)).forEach(s=>{const a=axes.find(v=>v.id===s.axis),span=a.range[1]-a.range[0]||1;x.strokeStyle=s.color;x.lineWidth=s.width||2;x.setLineDash(s.dash||[]);x.beginPath();let moved=false;data.forEach(p=>{if(!valid(p[s.key]))return;const v=+p[s.key],px=L+(p.t-t0)/(t1-t0)*PW,py=T+(a.range[1]-v)/span*PH;moved?x.lineTo(px,py):x.moveTo(px,py);moved=true});x.stroke()});x.setLineDash([]);x.fillStyle='#78918f';x.textAlign='left';x.fillText(new Date(t0*1000).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),L,h-8);x.textAlign='right';x.fillText(new Date(t1*1000).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'}),L+PW,h-8)}const cellW=w/series.length;x.textAlign='center';series.forEach((s,i)=>{const cx=cellW*(i+.5),dec=s.key==='hcho'||s.key==='temp'||s.key==='humidity'?1:0;x.fillStyle=s.color;x.font='600 10px system-ui';x.fillText(s.label,cx,13);x.font='12px system-ui';x.fillText(lastLive?fmt(lastLive[s.key],dec):'—',cx,31)})}
function drawAll(){drawChart('chartGas',[{key:'co2',label:'CO₂',color:'#58e0ac',axis:'co2'},{key:'voc',label:'VOC',color:'#f5c95a',axis:'voc'},{key:'hcho',label:'HCHO est.',color:'#ff7085',axis:'hcho'}],[{id:'co2',key:'co2',label:'CO₂ ppm',color:'#58e0ac',side:'left'},{id:'voc',key:'voc',label:'VOC index',color:'#f5c95a',side:'right'},{id:'hcho',key:'hcho',label:'HCHO estimé ppm',color:'#ff7085',side:'right'}]);drawChart('chartPm',[{key:'pm1',label:'PM1',color:'#70b7ff',axis:'pm',dash:[2,5],z:2},{key:'pm25',label:'PM2.5',color:'#a98bff',axis:'pm',dash:[8,5],z:1},{key:'pm10',label:'PM10',color:'#ff9066',axis:'pm',z:0}],[{id:'pm',keys:['pm1','pm25','pm10'],label:'µg/m³',color:'#a98bff',side:'left'}]);drawChart('chartClimate',[{key:'temp',label:'Temp.',color:'#ffb25f',axis:'temp'},{key:'humidity',label:'Hum.',color:'#62c9ff',axis:'hum'}],[{id:'temp',key:'temp',label:'Température °C',color:'#ffb25f',side:'left'},{id:'hum',key:'humidity',label:'Humidité %',color:'#62c9ff',side:'right'}])}
async function loadHistory(){const now=Math.floor(Date.now()/1000),data=await json(`/api/history?since=${now-rangeHours*3600}&max=900`);historyData=data.points||[];drawAll()}
function filteredEvents(){const date=$('eventDate').value,sensor=$('eventSensor').value;return eventsData.filter(e=>(!date||dayKey(e.start)===date)&&(!sensor||e.parameter===sensor))}
function dailyParts(e){const out=[];let start=e.start,end=e.end||e.start+e.duration;while(start<end){const d=new Date(start*1000),next=new Date(d.getFullYear(),d.getMonth(),d.getDate()+1).getTime()/1000,partEnd=Math.min(end,next);out.push({date:dayKey(start),seconds:partEnd-start});start=partEnd}return out}
function renderEvents(){const ev=filteredEvents(),body=$('eventBody');body.innerHTML=ev.length?ev.slice().reverse().map(e=>`<tr><td>${dt(e.start)}</td><td><span class="level">${e.parameter}</span></td><td>${duration(e.duration)}</td><td>${fmt(e.threshold,1)} ${e.unit}</td><td>${fmt(e.average,1)} ${e.unit}</td><td>${fmt(e.maximum,1)} ${e.unit}</td><td>${dt(e.end)}</td></tr>`).join(''):'<tr><td colspan="7" class="empty">Aucun dépassement pour ce filtre</td></tr>';const groups={};ev.forEach(e=>dailyParts(e).forEach(p=>{const k=p.date+'|'+e.parameter,g=groups[k]||(groups[k]={date:p.date,parameter:e.parameter,seconds:0,max:0,count:0,seen:new Set});g.seconds+=p.seconds;g.max=Math.max(g.max,+e.maximum||0);if(!g.seen.has(e.start)){g.seen.add(e.start);g.count++}}));const rows=Object.values(groups).sort((a,b)=>b.date.localeCompare(a.date));$('dailyBody').innerHTML=rows.length?rows.map(g=>`<tr><td>${new Date(g.date+'T12:00:00').toLocaleDateString('fr-FR')}</td><td>${g.parameter}</td><td>${duration(g.seconds)}</td><td>${fmt(g.max,1)}</td><td>${g.count}</td></tr>`).join(''):'<tr><td colspan="5" class="empty">Aucune synthèse disponible</td></tr>'}
async function loadEvents(){const d=await json('/api/events?max=200');eventsData=d.events||[];renderEvents()}
async function poll(){try{updateLive(await json('/api/live'));$('error').className='error'}catch(e){$('liveDot').className='dot stale';$('lastUpdate').textContent='Station inaccessible';$('error').textContent='Impossible de joindre la station. Nouvelle tentative automatique…';$('error').className='error show'}}
document.querySelectorAll('[data-chart-range] button').forEach(b=>b.onclick=async()=>{document.querySelectorAll('[data-chart-range] button').forEach(x=>x.classList.remove('active'));b.classList.add('active');rangeHours=+b.dataset.hours;await loadHistory()});$('eventDate').onchange=$('eventSensor').onchange=renderEvents;$('clearFilters').onclick=()=>{$('eventDate').value='';$('eventSensor').value='';renderEvents()};$('exportCsv').onclick=()=>location.href='/api/events.csv';addEventListener('resize',drawAll);new ResizeObserver(drawAll).observe(document.querySelector('.charts'));
(async()=>{await Promise.allSettled([loadHistory(),loadEvents(),poll()]);setInterval(poll,10000);setInterval(loadEvents,60000)})();
</script>
</body>
</html>
)EASEHTML";
